import Foundation
import NESCore

/// Generates Swift source containing a cartridge image, so an app can run
/// without shipping a `.nes` file.
///
/// This is the first step toward a ROM-free build. It does not reduce what the
/// app contains — the same bytes are there — but it removes the external file,
/// the bundle resource, and the "where is the ROM" failure mode entirely.
///
/// It also sets up the endgame. As routines are decompiled, the *code* regions
/// of this blob stop being executed, and the trace coverage map says exactly
/// which ranges those are. Once nothing reads a region, it can be pruned, and
/// what remains is the data the native game still needs.
enum EmbedROM {
    /// Base64 rather than a byte-array literal. A 131,072-element array literal
    /// is pathological for the Swift type checker; a handful of string
    /// constants compile instantly.
    static let chunkSize = 48 * 1024

    static func generate(
        romData: [UInt8],
        enumName: String,
        gameName: String
    ) -> String {
        let base64 = Data(romData).base64EncodedString()
        let chunks = stride(from: 0, to: base64.count, by: chunkSize).map { start -> String in
            let from = base64.index(base64.startIndex, offsetBy: start)
            let to = base64.index(from, offsetBy: min(chunkSize, base64.count - start))
            return String(base64[from..<to])
        }

        var lines: [String] = []
        lines.append("// Generated by `nesrun embed` — do not edit by hand.")
        lines.append("//")
        lines.append("// \(gameName) cartridge image, \(romData.count) bytes, embedded as")
        lines.append("// base64 so the app needs no .nes file at runtime.")
        lines.append("//")
        lines.append("// Base64 rather than a byte-array literal: a \(romData.count)-element")
        lines.append("// array literal is pathological for the Swift type checker, while a few")
        lines.append("// string constants compile instantly.")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        lines.append("public enum \(enumName) {")
        lines.append("    /// Size of the decoded image, for a cheap sanity check.")
        lines.append("    public static let byteCount = \(romData.count)")
        lines.append("")
        lines.append("    /// The decoded cartridge image.")
        lines.append("    public static var bytes: [UInt8] {")
        lines.append("        var combined = \"\"")
        lines.append("        combined.reserveCapacity(\(base64.count))")
        lines.append("        for chunk in chunks { combined += chunk }")
        lines.append("        guard let data = Data(base64Encoded: combined) else { return [] }")
        lines.append("        return [UInt8](data)")
        lines.append("    }")
        lines.append("")
        lines.append("    private static let chunks: [String] = [")
        for chunk in chunks {
            lines.append("        \"\(chunk)\",")
        }
        lines.append("    ]")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
